server:
  port: 8080
  address: 0.0.0.0
  servlet:
    context-path: /superstore

spring:
  config:
    activate:
      on-profile: develop
  output:
    ansi:
      enabled: always
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    # database-platform: org.hibernate.spatial.dialect.mysql.MySQL56InnoDBSpatialDialect
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/superstore
    username: tmax
    password: tmax
  sql:
    init:
      platform: develop
      mode: always
      continue-on-error: true

logging:
  level:
    # root: trace
    org:
      hibernate:
        sql: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

---
# integration test profile
spring:
  config:
    activate:
      on-profile: develop-integration-test
  datasource:
    url: jdbc:h2:mem:mydb
    username: tmax
    password: tmax
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  sql:
    init:
      platform: integration-test-h2

---
# develop server profile
spring:
  config:
    activate:
      on-profile: develop-server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DATABASE_HOST:localhost}:3306/superstore
    username: tmax
    password: tmax

---
# 한상준's profile
server:
  port: 8081

spring:
  config:
    activate:
      on-profile: develop-hsj
  datasource:
    url: jdbc:mysql://localhost:3307/superstore
    username: tmax
    password: tmax
  # https://docs.spring.io/spring-boot/docs/2.7.2/reference/htmlsingle/#howto.data-initialization.using-basic-sql-scripts
  jpa:
    defer-datasource-initialization: true
  sql:
    init:
      platform: develop
      mode: always
      continue-on-error: true
