spring:
  config:
    import:
    - classpath:application-develop.yml
  profiles:
    group:
      develop: develop
      develop-server: develop, develop-server
      develop-hsj: develop, develop-hsj
    active: develop # 실행 원하는 spring.profiles.group 지정