spring:
  config:
    import:
    - classpath:application-develop.yml
    - classpath:email.yml
  profiles:
    group:
      develop: develop
      develop-server: develop, develop-server
      develop-hsj: develop, develop-hsj
    active: develop # 실행 원하는 spring.profiles.group 지정

jwt:
  header: Authorization
  secret: Z3VuLWpvby1haG4tand0LXNlY3JldC1ndW4tam9vLWFobi1qd3Qtc2VjcmV0LWd1bi1qb28tYWhuLWp3dC1zZWNyZXQtZ3VuLWpvby1haG4tand0LXNlY3JldC1oZWxsbw==
  token-validity-in-seconds: 86400
