server:
  port: 8080
  address: 0.0.0.0
  servlet:
    context-path: /superstore

spring:
  config:
    activate:
      on-profile: develop
  output:
    ansi:
      enabled: always
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    # database-platform: org.hibernate.spatial.dialect.mysql.MySQL56InnoDBSpatialDialect
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/superstore
    username: tmax
    password: tmax
  sql:
    init:
      data-locations: classpath:develop_sql/*
      mode: always
      continue-on-error: true
  data:
    redis:
      repositories:
        enabled: false
#  redis:
#    host: localhost
#    port: 6379
#    password: tmax

logging:
  level:
    # root: trace
    org:
      hibernate:
        sql: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

---
# integration test profile
spring:
  config:
    activate:
      on-profile: develop-integration-test
  datasource:
    url: jdbc:h2:mem:mydb;MODE=MySQL
    username: tmax
    password: tmax
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  sql:
    init:
      data-locations: classpath:integration-test-h2_sql/*

---
# develop server profile
spring:
  config:
    activate:
      on-profile: develop-server
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DATABASE_HOST:localhost}:3306/superstore
    username: tmax
    password: tmax

---
# 한상준's profile
server:
  port: 8081

spring:
  config:
    activate:
      on-profile: develop-hsj
  datasource:
    url: jdbc:mysql://localhost:3307/superstore
    username: tmax
    password: tmax
  # https://docs.spring.io/spring-boot/docs/2.7.2/reference/htmlsingle/#howto.data-initialization.using-basic-sql-scripts
  jpa:
    defer-datasource-initialization: true
  sql:
    init:
      data-locations: classpath:develop_sql/*
      mode: always
      # continue-on-error: false

---
server:
  port: 8081

spring:
  config:
    activate:
      on-profile: develop-cjh
  output:
    ansi:
      enabled: always
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/superstore
    username: root
    password: 1234
  jpa:
    show-sql: true
    defer-datasource-initialization: true
    generate-ddl: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        ddl-auto: update
        format_sql: true
  sql:
    init:
      data-locations: classpath:develop_sql/*
      mode: always
      # continue-on-error: true
      # continue-on-error: false

---
# 조현준's profile
server:
  port: 8081

spring:
  config:
    activate:
      on-profile: develop-chj
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/superstore
    username: tmax
    password: tmax
  jpa:
    show-sql: true
    defer-datasource-initialization: true
    generate-ddl: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        ddl-auto: create
        format_sql: true
  sql:
    init:
      data-locations: classpath:develop_sql/*
      mode: always
---
