pipeline {
    agent any
    parameters {
        string(name: 'BRANCH', defaultValue: '*/master', description: 'checkout branch')
    }
    environment {
        DISCORD_WEBHOOK_URL = 'https://discord.com/api/webhooks/1012228864346443827/mAKrRlMJ0g5bN7OGCnUfNVLkzs18SxXXXEDrGVRegPhd1Y05onul4GFxroP-50AAvP3l'
        FAILURE_TITLE = '빌드 오류'
        FAILURE_REASON = 'unknown'
    }
    
    stages {
        stage('Checkout') {
            steps {
                echo "current branch: ${params.BRANCH}"
                checkout([$class: 'GitSCM', branches: [[name: "${params.BRANCH}"]], extensions: [], userRemoteConfigs: [[credentialsId: 'jenkins-ssh', url: 'git@192.168.155.43:tmax-am/superstore-backend.git']]])
            }
        }

        stage('Test') {
            steps {
                script {
                    try {
                        def output = sh(script: './gradlew clean test', returnStdout: true)
                    } catch (err) {
                        FAILURE_TITLE = 'gradle test 실패'
                        FAILURE_REASON = output
                    }
                }
            }
        }

        stage('Gradle Build') {
            steps {
                sh './gradlew openapi3'
                sh './gradlew build'
            }
        }

        stage('Docker Build') {
            steps {
                script  {
                    try {
                        sh 'docker-compose --env-file ./deploy/.env -f ./deploy/docker-compose.yml down --rmi all'
                    } catch (err) {
                        echo "failed to remove docker-compose: ${err}"
                    } finally {
                        sh 'docker-compose --env-file ./deploy/.env -f ./deploy/docker-compose.yml up -d'
                    }
                }
            }
        }
    }

    post {
        fixed { // 빌드 결과가 이전 실패 > 성공으로 전환됨
            script {
                String sendMessage = '''
[ 빌드 성공 ]
스프링 주소 : http://192.168.159.41:18080/
Swagger 주소 :  http://192.168.159.41:28080/
DB 주소 : 192.168.159.41:13306
                    '''

                discordSend description: sendMessage,
                        link: env.BUILD_URL,
                        result: currentBuild.currentResult,
                        title: JOB_NAME,
                        webhookURL: DISCORD_WEBHOOK_URL
            }
        }

        unsuccessful {
            script {
                String sendMessage = """
[ ${FAILURE_TITLE} ]
${FAILURE_REASON}
            """

                discordSend description: sendMessage,
                    link: "${env.BUILD_URL}console",
                    result: currentBuild.currentResult,
                    title: JOB_NAME,
                    webhookURL: DISCORD_WEBHOOK_URL
            }
        }
    }
}
